base:
    url: http://192.168.3.5:8080
spring:
    flyway:
        enabled: 'false'
        schemas: migrations
        baselineOnMigrate: 'true'
        locations: classpath:db/migration
        url: jdbc:postgresql://db:5432/soundhub
        user: postgres
        password: postgres
    kafka:
        bootstrap-servers: 'localhost:9092'
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        username: postgres
        url: jdbc:postgresql://db:5432/soundhub
    cache:
        type: redis
    data:
        redis:
            host: redis
            port: '6379'
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    web:
        resources:
            add-mappings: 'false'
refreshToken:
    expirationInMs: '604800000'
s3:
    region: ru-central-1
    key:
        id: 503c84bcdd9025d9ee77fdae38d93c66
        secret: 4c1d7afda68640062bad30d8ecb078d2
    endpoint: https://s3.cloud.ru
    bucket:
        tenantId: 0036d059-3e1d-4e87-b2f5-785bd6fedc5c
        name: bucket-c9e192
recommendation:
    url: http://192.168.3.5:8888/recommend
logging:
    level:
        com:
            soundhub:
                api: DEBUG
        org:
            hibernate:
                transaction: DEBUG
            springframework:
                transaction: DEBUG
media:
    source: s3
    folder:
        posts: posts/
        genres: genres/
        avatars: avatars/
        static: static/
project:
#    Production
    resources:
        path: resources
#    resources:
#        path: src/main/resources
token:
    signing:
        expirationInMs: '3600000'
        key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
